# Workflow for testing that the code of incoming pull requests builds, validates, and follows style guidelines

name: PR Checks

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

concurrency: pr-${{ github.ref }}
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out pull request
        uses: actions/checkout@v3
      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'
      - name: Build and test with Maven
        run: mvn clean verify -B

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out pull request
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'
      - name: Run linter/checker
        run: mvn compile -B -P lint,strict

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - name: Check out pull request
        uses: actions/checkout@v3
      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'
      - name: Run style checker
        run: mvn validate -B -P style,strict